project:
  type: website

website:
  title: "Wouter Weeda, PhD"
  navbar: 
    background: secondary
    search: true
    left: 
      - text: "Home"
        href: index.qmd
      - about.qmd
      - publications.qmd
    tools:
      - icon: github
        href: https://github.com/wdweeda/
        
    
  sidebar:
    style: "floating"
    search: false
    contents:
      - text: "Home"
        href: index.qmd
     
    tools: 
      - icon: github
        href: https://github.com/wdweeda/
         
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css">

